# Generated by Django 4.2.2 on 2024-11-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="название статьи"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="URL"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_photo/%Y/%m/%d/",
                        verbose_name="фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="опубликовано"),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="наименование категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog_photo/%Y/%m/%d/",
                        verbose_name="фото",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название продукта"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products_photo/%Y/%m/%d/",
                        verbose_name="фото",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="цена за товар")),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров продукта",
                        verbose_name="количество просмотров",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "permissions": [
                    ("can_edit_is_published", "Can edit publication"),
                    ("edit_description", "Сan edit description"),
                    ("edit_category", "Сan edit category"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numb",
                    models.PositiveIntegerField(default=0, verbose_name="номер версии"),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название версии"),
                ),
                (
                    "is_actual",
                    models.BooleanField(default=True, verbose_name="Текущая версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="продукт",
                        to="catalog.product",
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
                "ordering": ["product", "numb", "name", "is_actual"],
            },
        ),
    ]
