# Generated by Django 5.1 on 2024-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_photo_alter_product_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров продукта",
                verbose_name="количество просмотров",
            ),
        ),
    ]
