# Generated by Django 5.1 on 2024-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_photo/%Y/%m/%d/",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publication_attribute",
            field=models.BooleanField(default=False, verbose_name="опубликовано"),
        ),
    ]
