# Generated by Django 5.1 on 2024-08-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_blog_photo_alter_blog_publication_attribute"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="publication_attribute",
            new_name="is_published",
        ),
    ]
