# Generated by Django 5.1 on 2024-10-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_blog_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numb",
                    models.PositiveIntegerField(default=0, verbose_name="номер версии"),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название версии"),
                ),
                (
                    "is_actual",
                    models.BooleanField(default=True, verbose_name="Текущая версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version",
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
                "ordering": ["product", "numb", "name", "is_actual"],
            },
        ),
    ]
